[2023-01-17T15:48:40.489+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark.spark_job manual__2023-01-17T15:47:42.630668+00:00 [queued]>
[2023-01-17T15:48:40.518+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark.spark_job manual__2023-01-17T15:47:42.630668+00:00 [queued]>
[2023-01-17T15:48:40.519+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T15:48:40.519+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-17T15:48:40.520+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T15:48:40.564+0000] {taskinstance.py:1383} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2023-01-17 15:47:42.630668+00:00
[2023-01-17T15:48:40.573+0000] {standard_task_runner.py:54} INFO - Started process 22 to run task
[2023-01-17T15:48:40.580+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'spark', 'spark_job', 'manual__2023-01-17T15:47:42.630668+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmp28bxqk9e']
[2023-01-17T15:48:40.584+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask spark_job
[2023-01-17T15:48:40.587+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/repo/Airflow/dags/spark_dag.py
[2023-01-17T15:48:47.069+0000] {task_command.py:384} INFO - Running <TaskInstance: spark.spark_job manual__2023-01-17T15:47:42.630668+00:00 [running]> on host sparksparkjob-852b1d47d73a4a89894c0cfb8b432ff0
[2023-01-17T15:48:47.374+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spark
AIRFLOW_CTX_TASK_ID=spark_job
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T15:47:42.630668+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T15:47:42.630668+00:00
[2023-01-17T15:48:47.401+0000] {base.py:71} INFO - Using connection ID 'spark_default' for task execution.
[2023-01-17T15:48:47.403+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master spark://10.96.144.83 :7077 --name arrow-spark spark-app.py
[2023-01-17T15:48:47.718+0000] {spark_submit.py:495} INFO - /home/airflow/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-17T15:48:53.381+0000] {spark_submit.py:495} INFO - python3: can't open file '/opt/airflow/spark-app.py': [Errno 2] No such file or directory
[2023-01-17T15:48:53.420+0000] {spark_submit.py:495} INFO - 23/01/17 15:48:53 INFO ShutdownHookManager: Shutdown hook called
[2023-01-17T15:48:53.427+0000] {spark_submit.py:495} INFO - 23/01/17 15:48:53 INFO ShutdownHookManager: Deleting directory /tmp/spark-1cf90b25-75e9-4d4e-a605-ade380ba878e
[2023-01-17T15:48:53.570+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 427, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://10.96.144.83 :7077 --name arrow-spark spark-app.py. Error code is: 2.
[2023-01-17T15:48:53.580+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=spark, task_id=spark_job, execution_date=20230117T154742, start_date=20230117T154840, end_date=20230117T154853
[2023-01-17T15:48:53.620+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task spark_job (Cannot execute: spark-submit --master spark://10.96.144.83 :7077 --name arrow-spark spark-app.py. Error code is: 2.; 22)
[2023-01-17T15:48:53.721+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-17T15:48:53.769+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
