[2023-01-18T04:52:27.194+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark.spark_job manual__2023-01-18T04:51:40.283843+00:00 [queued]>
[2023-01-18T04:52:27.219+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark.spark_job manual__2023-01-18T04:51:40.283843+00:00 [queued]>
[2023-01-18T04:52:27.220+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T04:52:27.220+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-18T04:52:27.221+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T04:52:27.260+0000] {taskinstance.py:1383} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2023-01-18 04:51:40.283843+00:00
[2023-01-18T04:52:27.266+0000] {standard_task_runner.py:54} INFO - Started process 21 to run task
[2023-01-18T04:52:27.273+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'spark', 'spark_job', 'manual__2023-01-18T04:51:40.283843+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmpuyxtw5d4']
[2023-01-18T04:52:27.276+0000] {standard_task_runner.py:83} INFO - Job 38: Subtask spark_job
[2023-01-18T04:52:27.279+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/repo/Airflow/dags/spark_dag.py
[2023-01-18T04:52:34.631+0000] {task_command.py:384} INFO - Running <TaskInstance: spark.spark_job manual__2023-01-18T04:51:40.283843+00:00 [running]> on host sparksparkjob-3e631df52b33459bba7f70886c06fb25
[2023-01-18T04:52:34.928+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spark
AIRFLOW_CTX_TASK_ID=spark_job
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T04:51:40.283843+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T04:51:40.283843+00:00
[2023-01-18T04:52:34.953+0000] {base.py:71} INFO - Using connection ID 'spark_default' for task execution.
[2023-01-18T04:52:34.955+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master spark://10.96.144.83 :7077 --name arrow-spark spark-app.py
[2023-01-18T04:52:35.258+0000] {spark_submit.py:495} INFO - /home/airflow/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-18T04:52:41.526+0000] {spark_submit.py:495} INFO - python3: can't open file '/opt/airflow/spark-app.py': [Errno 2] No such file or directory
[2023-01-18T04:52:41.569+0000] {spark_submit.py:495} INFO - 23/01/18 04:52:41 INFO ShutdownHookManager: Shutdown hook called
[2023-01-18T04:52:41.577+0000] {spark_submit.py:495} INFO - 23/01/18 04:52:41 INFO ShutdownHookManager: Deleting directory /tmp/spark-b6bdf7dc-03ce-4728-994b-18dd0491494a
[2023-01-18T04:52:41.713+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 427, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://10.96.144.83 :7077 --name arrow-spark spark-app.py. Error code is: 2.
[2023-01-18T04:52:41.726+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=spark, task_id=spark_job, execution_date=20230118T045140, start_date=20230118T045227, end_date=20230118T045241
[2023-01-18T04:52:41.765+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task spark_job (Cannot execute: spark-submit --master spark://10.96.144.83 :7077 --name arrow-spark spark-app.py. Error code is: 2.; 21)
[2023-01-18T04:52:41.860+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-18T04:52:41.918+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
